### PR TITLE
Improve formatting

### PR DESCRIPTION
**Pull request by TheKodeToad**
This was annoying me. I didn't look into it much, but this should work.

### CODE REVIEW

**Comment by Earthcomputer** [comment]
You need to update the expected test outputs.

**Comment by zml2008** [comment]
removing some fernflower charm here, that'd be the end of an era :3

**Comment by TheKodeToad** [comment]
Oops! This was just a quick fix with no understanding of how the code actually works.
Tests are passing now.

**Comment by Desoroxxx** [comment]
I hope this can make it soon this looks wonderful

**Comment by jaskarth** [comment]
Thanks for this! I'll integrate it and resolve the issues.

**Comment by TheKodeToad** [comment]
I'm sorry for not getting it to work :P. It worked fine locally which is weird!

**Comment by jaskarth** [comment]
Nah, it's all good! Updating all of the tests is fairly tedious, but I have a system to fix that automatically so I wanted to go ahead and apply that 😄

**Comment by TheKodeToad** [comment]
Yayy!

**Pull request merged**
