### PR TITLE
Upstream GitHub Actions and other libraries.

### PR DESCRIPTION
**Pull request by Kichura**
Drafted for now because this PR has failed 8 tests in a row which was the SingleClassesTest - Guessing it wasn't happy with one or more upstreamed packages.

### CODE REVIEW

**Comment by zml2008** [comment]
My first guess would be you pumped the kotlin dependency which changed the compiled kotlin bytecode which caused the tests to fail. Read through the test results, they show you what failed.

**Review by Kichura — COMMENTED** [review]
Yup this works, This was [totally] a fun roller coaster to ride.

**Review by SuperCoder7979 — APPROVED** [review]
Looks good, will merge when dev/1.9.0 is merged into main.

**Comment by SuperCoder7979** [comment]
Seems like there's a conflict, will merge after it's resolved

**Review by Kichura — COMMENTED** [review]
This should be checked before hand though.

**Comment by SuperCoder7979** [comment]
Finally got around to looking at it, looks good for the most part! Two scala tests fail due to the changed version, I'll push those tessts, wait for GHA to finish, then merge.

**Review by SuperCoder7979 — APPROVED** [review]

**Comment by Kichura** [comment]
> Finally got around to looking at it, looks good for the most part! Two scala tests fail due to the changed version, I'll push those tessts, wait for GHA to finish, then merge.

CommandTest (Line 36, 58 and 80), BulkDecompilationTest (Line 42) and AssertionFailureBuilder.java (Line 151) failed.

**Comment by SuperCoder7979** [comment]
I think those issues are regarding the test code itself and not the CI- I'll take care of it after it's merged.

**Pull request merged**
